### ISSUE TITLE
LibSVM missing

### ISSUE THREAD

**Issue by mare24** [rjmarsan/Weka-for-Android#3]
This version does not contain LibSVM. I am unable to find which version of Weka this is?

**Comment by fengpingma** [comment]
I export this project into Android Studio,but it didn't work.
I meet an EXCEPTION as follows:
09-28 09:15:47.889 12928-12928/weka.weka W/System: ClassLoader referenced unknown path: /data/app/weka.weka-2/lib/arm64
09-28 09:15:47.901 12928-12928/weka.weka D/AndroidRuntime: Shutting down VM
09-28 09:15:47.903 12928-12928/weka.weka E/AndroidRuntime: FATAL EXCEPTION: main
                                                           Process: weka.weka, PID: 12928
                                                           java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{weka.weka/weka.weka.Weka}: java.lang.ClassNotFoundException: Didn't find class "weka.weka.Weka" on path: DexPathList[[zip file "/data/app/weka.weka-2/base.apk"],nativeLibraryDirectories=[/data/app/weka.weka-2/lib/arm64, /system/lib64, /vendor/lib64]]
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2567)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:154)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "weka.weka.Weka" on path: DexPathList[[zip file "/data/app/weka.weka-2/base.apk"],nativeLibraryDirectories=[/data/app/weka.weka-2/lib/arm64, /system/lib64, /vendor/lib64]]
                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                               at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:154) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
